// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TextDifficultyDeterminer.Infrastructure.Migrations
{
    [DbContext(typeof(TextDifficultyDbContext))]
    [Migration("20240111162329_MySQLNewMigration")]
    partial class MySQLNewMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FrequencyWord", b =>
                {
                    b.Property<Guid>("FrequencyWordId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("char(255)");

                    b.Property<long>("DifficultyScore")
                        .HasColumnType("bigint");

                    b.Property<long>("FrequencyOfWord")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Language")
                        .HasMaxLength(255)
                        .HasColumnType("char(255)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FrequencyWordId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("char(255)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });
#pragma warning restore 612, 618
        }
    }
}
